################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ns3-mmwave/bindings/python \
ns3-mmwave/build/scratch \
ns3-mmwave/build/scratch/subdir \
ns3-mmwave/build/src/antenna/model \
ns3-mmwave/build/src/aodv/helper \
ns3-mmwave/build/src/aodv/model \
ns3-mmwave/build/src/applications/helper \
ns3-mmwave/build/src/applications/model \
ns3-mmwave/build/src/bridge/helper \
ns3-mmwave/build/src/bridge/model \
ns3-mmwave/build/src/buildings/helper \
ns3-mmwave/build/src/buildings/model \
ns3-mmwave/build/src/config-store/model \
ns3-mmwave/build/src/core/helper \
ns3-mmwave/build/src/core/model \
ns3-mmwave/build/src/csma/helper \
ns3-mmwave/build/src/csma/model \
ns3-mmwave/build/src/csma-layout/model \
ns3-mmwave/build/src/dsdv/helper \
ns3-mmwave/build/src/dsdv/model \
ns3-mmwave/build/src/dsr/helper \
ns3-mmwave/build/src/dsr/model \
ns3-mmwave/build/src/energy/helper \
ns3-mmwave/build/src/energy/model \
ns3-mmwave/build/src/fd-net-device/helper \
ns3-mmwave/build/src/fd-net-device/model \
ns3-mmwave/build/src/flow-monitor/helper \
ns3-mmwave/build/src/flow-monitor/model \
ns3-mmwave/build/src/internet/helper \
ns3-mmwave/build/src/internet/model \
ns3-mmwave/build/src/internet-apps/helper \
ns3-mmwave/build/src/internet-apps/model \
ns3-mmwave/build/src/lr-wpan/helper \
ns3-mmwave/build/src/lr-wpan/model \
ns3-mmwave/build/src/lte/helper \
ns3-mmwave/build/src/lte/model \
ns3-mmwave/build/src/mesh/helper/dot11s \
ns3-mmwave/build/src/mesh/helper/flame \
ns3-mmwave/build/src/mesh/helper \
ns3-mmwave/build/src/mesh/model/dot11s \
ns3-mmwave/build/src/mesh/model/flame \
ns3-mmwave/build/src/mesh/model \
ns3-mmwave/build/src/mmwave/helper \
ns3-mmwave/build/src/mmwave/model \
ns3-mmwave/build/src/mobility/helper \
ns3-mmwave/build/src/mobility/model \
ns3-mmwave/build/src/mpi/model \
ns3-mmwave/build/src/netanim/model \
ns3-mmwave/build/src/network/helper \
ns3-mmwave/build/src/network/model \
ns3-mmwave/build/src/network/utils \
ns3-mmwave/build/src/nix-vector-routing/helper \
ns3-mmwave/build/src/nix-vector-routing/model \
ns3-mmwave/build/src/olsr/helper \
ns3-mmwave/build/src/olsr/model \
ns3-mmwave/build/src/point-to-point/helper \
ns3-mmwave/build/src/point-to-point/model \
ns3-mmwave/build/src/point-to-point-layout/model \
ns3-mmwave/build/src/propagation/model \
ns3-mmwave/build/src/sixlowpan/helper \
ns3-mmwave/build/src/sixlowpan/model \
ns3-mmwave/build/src/spectrum/helper \
ns3-mmwave/build/src/spectrum/model \
ns3-mmwave/build/src/stats/helper \
ns3-mmwave/build/src/stats/model \
ns3-mmwave/build/src/tap-bridge/helper \
ns3-mmwave/build/src/tap-bridge/model \
ns3-mmwave/build/src/topology-read/helper \
ns3-mmwave/build/src/topology-read/model \
ns3-mmwave/build/src/traffic-control/helper \
ns3-mmwave/build/src/traffic-control/model \
ns3-mmwave/build/src/uan/helper \
ns3-mmwave/build/src/uan/model \
ns3-mmwave/build/src/virtual-net-device/model \
ns3-mmwave/build/src/wave/helper \
ns3-mmwave/build/src/wave/model \
ns3-mmwave/build/src/wifi/helper \
ns3-mmwave/build/src/wifi/model \
ns3-mmwave/build/src/wimax/helper \
ns3-mmwave/build/src/wimax/model \
ns3-mmwave/build/utils \
ns3-mmwave/examples/energy \
ns3-mmwave/examples/error-model \
ns3-mmwave/examples/ipv6 \
ns3-mmwave/examples/matrix-topology \
ns3-mmwave/examples/naming \
ns3-mmwave/examples/realtime \
ns3-mmwave/examples/routing \
ns3-mmwave/examples/socket \
ns3-mmwave/examples/stats \
ns3-mmwave/examples/tcp \
ns3-mmwave/examples/traffic-control \
ns3-mmwave/examples/tutorial \
ns3-mmwave/examples/udp \
ns3-mmwave/examples/udp-client-server \
ns3-mmwave/examples/wireless \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/benchmarks \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_1f933b02106127ce3a9f4633a0e368e7 \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_1f933b02106127ce3a9f4633a0e368e7/testbuild \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_3b2479b91ea1f8aedc2bbc867fa4858e \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_3b2479b91ea1f8aedc2bbc867fa4858e/testbuild \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_f3cbea3d49a46bf16c8e1d8029b9164d \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_f3cbea3d49a46bf16c8e1d8029b9164d/testbuild \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_fa0c4ec9c63ac505501cc0863d9bdc48 \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_fa0c4ec9c63ac505501cc0863d9bdc48/testbuild \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_fe0ca542f39064c5a14ee41a2e983996 \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/build/.conf_check_fe0ca542f39064c5a14ee41a2e983996/testbuild \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/a \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/b \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/boost_shared_ptr \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/buffer \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/c \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/callback \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/d \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/e \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/f \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/g \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/h \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/examples/std_shared_ptr \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/tests/boost \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/tests/c-hello \
ns3-mmwave/pybindgen-0.17.0.post57+nga6376f2/tests \
ns3-mmwave/scratch \
ns3-mmwave/scratch/subdir \
ns3-mmwave/src/antenna/model \
ns3-mmwave/src/antenna/test \
ns3-mmwave/src/aodv/examples \
ns3-mmwave/src/aodv/helper \
ns3-mmwave/src/aodv/model \
ns3-mmwave/src/aodv/test \
ns3-mmwave/src/applications/helper \
ns3-mmwave/src/applications/model \
ns3-mmwave/src/applications/test \
ns3-mmwave/src/bridge/examples \
ns3-mmwave/src/bridge/helper \
ns3-mmwave/src/bridge/model \
ns3-mmwave/src/brite/examples \
ns3-mmwave/src/brite/helper \
ns3-mmwave/src/brite/test \
ns3-mmwave/src/buildings/examples \
ns3-mmwave/src/buildings/helper \
ns3-mmwave/src/buildings/model \
ns3-mmwave/src/buildings/test \
ns3-mmwave/src/click/examples \
ns3-mmwave/src/click/helper \
ns3-mmwave/src/click/model \
ns3-mmwave/src/click/test \
ns3-mmwave/src/config-store/examples \
ns3-mmwave/src/config-store/model \
ns3-mmwave/src/core/bindings \
ns3-mmwave/src/core/examples \
ns3-mmwave/src/core/helper \
ns3-mmwave/src/core/model \
ns3-mmwave/src/core/test \
ns3-mmwave/src/csma/examples \
ns3-mmwave/src/csma/helper \
ns3-mmwave/src/csma/model \
ns3-mmwave/src/csma-layout/examples \
ns3-mmwave/src/csma-layout/model \
ns3-mmwave/src/dsdv/examples \
ns3-mmwave/src/dsdv/helper \
ns3-mmwave/src/dsdv/model \
ns3-mmwave/src/dsdv/test \
ns3-mmwave/src/dsr/examples \
ns3-mmwave/src/dsr/helper \
ns3-mmwave/src/dsr/model \
ns3-mmwave/src/dsr/test \
ns3-mmwave/src/energy/examples \
ns3-mmwave/src/energy/helper \
ns3-mmwave/src/energy/model \
ns3-mmwave/src/energy/test \
ns3-mmwave/src/fd-net-device/examples \
ns3-mmwave/src/fd-net-device/helper \
ns3-mmwave/src/fd-net-device/model \
ns3-mmwave/src/flow-monitor/helper \
ns3-mmwave/src/flow-monitor/model \
ns3-mmwave/src/flow-monitor/test \
ns3-mmwave/src/internet/examples \
ns3-mmwave/src/internet/helper \
ns3-mmwave/src/internet/model \
ns3-mmwave/src/internet/test \
ns3-mmwave/src/internet-apps/helper \
ns3-mmwave/src/internet-apps/model \
ns3-mmwave/src/lr-wpan/examples \
ns3-mmwave/src/lr-wpan/helper \
ns3-mmwave/src/lr-wpan/model \
ns3-mmwave/src/lr-wpan/test \
ns3-mmwave/src/lte/examples \
ns3-mmwave/src/lte/helper \
ns3-mmwave/src/lte/model \
ns3-mmwave/src/lte/test \
ns3-mmwave/src/mesh/examples \
ns3-mmwave/src/mesh/helper/dot11s \
ns3-mmwave/src/mesh/helper/flame \
ns3-mmwave/src/mesh/helper \
ns3-mmwave/src/mesh/model/dot11s \
ns3-mmwave/src/mesh/model/flame \
ns3-mmwave/src/mesh/model \
ns3-mmwave/src/mesh/test/dot11s \
ns3-mmwave/src/mesh/test/flame \
ns3-mmwave/src/mesh/test \
ns3-mmwave/src/mmwave/examples \
ns3-mmwave/src/mmwave/helper \
ns3-mmwave/src/mmwave/model \
ns3-mmwave/src/mmwave/test \
ns3-mmwave/src/mobility/examples \
ns3-mmwave/src/mobility/helper \
ns3-mmwave/src/mobility/model \
ns3-mmwave/src/mobility/test \
ns3-mmwave/src/mpi/examples \
ns3-mmwave/src/mpi/model \
ns3-mmwave/src/netanim/examples \
ns3-mmwave/src/netanim/model \
ns3-mmwave/src/netanim/test \
ns3-mmwave/src/network/examples \
ns3-mmwave/src/network/helper \
ns3-mmwave/src/network/model \
ns3-mmwave/src/network/test \
ns3-mmwave/src/network/utils \
ns3-mmwave/src/nix-vector-routing/examples \
ns3-mmwave/src/nix-vector-routing/helper \
ns3-mmwave/src/nix-vector-routing/model \
ns3-mmwave/src/olsr/examples \
ns3-mmwave/src/olsr/helper \
ns3-mmwave/src/olsr/model \
ns3-mmwave/src/olsr/test \
ns3-mmwave/src/openflow/examples \
ns3-mmwave/src/openflow/helper \
ns3-mmwave/src/openflow/model \
ns3-mmwave/src/openflow/test \
ns3-mmwave/src/point-to-point/examples \
ns3-mmwave/src/point-to-point/helper \
ns3-mmwave/src/point-to-point/model \
ns3-mmwave/src/point-to-point/test \
ns3-mmwave/src/point-to-point-layout/model \
ns3-mmwave/src/propagation/examples \
ns3-mmwave/src/propagation/model \
ns3-mmwave/src/propagation/test \
ns3-mmwave/src/sixlowpan/examples \
ns3-mmwave/src/sixlowpan/helper \
ns3-mmwave/src/sixlowpan/model \
ns3-mmwave/src/sixlowpan/test \
ns3-mmwave/src/spectrum/examples \
ns3-mmwave/src/spectrum/helper \
ns3-mmwave/src/spectrum/model \
ns3-mmwave/src/spectrum/test \
ns3-mmwave/src/stats/examples \
ns3-mmwave/src/stats/helper \
ns3-mmwave/src/stats/model \
ns3-mmwave/src/stats/test \
ns3-mmwave/src/tap-bridge/examples \
ns3-mmwave/src/tap-bridge/helper \
ns3-mmwave/src/tap-bridge/model \
ns3-mmwave/src/test \
ns3-mmwave/src/test/ns3tc \
ns3-mmwave/src/test/ns3tcp \
ns3-mmwave/src/test/ns3wifi \
ns3-mmwave/src/test/perf \
ns3-mmwave/src/test/traced \
ns3-mmwave/src/topology-read/examples \
ns3-mmwave/src/topology-read/helper \
ns3-mmwave/src/topology-read/model \
ns3-mmwave/src/topology-read/test \
ns3-mmwave/src/traffic-control/examples \
ns3-mmwave/src/traffic-control/helper \
ns3-mmwave/src/traffic-control/model \
ns3-mmwave/src/traffic-control/test \
ns3-mmwave/src/uan/examples \
ns3-mmwave/src/uan/helper \
ns3-mmwave/src/uan/model \
ns3-mmwave/src/uan/test \
ns3-mmwave/src/virtual-net-device/examples \
ns3-mmwave/src/virtual-net-device/model \
ns3-mmwave/src/visualizer/model \
ns3-mmwave/src/wave/examples \
ns3-mmwave/src/wave/helper \
ns3-mmwave/src/wave/model \
ns3-mmwave/src/wave/test \
ns3-mmwave/src/wifi/examples \
ns3-mmwave/src/wifi/helper \
ns3-mmwave/src/wifi/model \
ns3-mmwave/src/wifi/test \
ns3-mmwave/src/wimax/examples \
ns3-mmwave/src/wimax/helper \
ns3-mmwave/src/wimax/model \
ns3-mmwave/src/wimax/test \
ns3-mmwave/utils \

