################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../ns3-mmwave/src/wifi/model/aarf-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/aarfcd-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/adhoc-wifi-mac.cc \
../ns3-mmwave/src/wifi/model/ampdu-subframe-header.cc \
../ns3-mmwave/src/wifi/model/ampdu-tag.cc \
../ns3-mmwave/src/wifi/model/amrr-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/amsdu-subframe-header.cc \
../ns3-mmwave/src/wifi/model/ap-wifi-mac.cc \
../ns3-mmwave/src/wifi/model/aparf-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/arf-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/block-ack-agreement.cc \
../ns3-mmwave/src/wifi/model/block-ack-cache.cc \
../ns3-mmwave/src/wifi/model/block-ack-manager.cc \
../ns3-mmwave/src/wifi/model/capability-information.cc \
../ns3-mmwave/src/wifi/model/cara-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/constant-rate-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/ctrl-headers.cc \
../ns3-mmwave/src/wifi/model/dca-txop.cc \
../ns3-mmwave/src/wifi/model/dcf-manager.cc \
../ns3-mmwave/src/wifi/model/dcf-state.cc \
../ns3-mmwave/src/wifi/model/dsss-error-rate-model.cc \
../ns3-mmwave/src/wifi/model/dsss-parameter-set.cc \
../ns3-mmwave/src/wifi/model/edca-parameter-set.cc \
../ns3-mmwave/src/wifi/model/edca-txop-n.cc \
../ns3-mmwave/src/wifi/model/erp-information.cc \
../ns3-mmwave/src/wifi/model/error-rate-model.cc \
../ns3-mmwave/src/wifi/model/he-capabilities.cc \
../ns3-mmwave/src/wifi/model/ht-capabilities.cc \
../ns3-mmwave/src/wifi/model/ht-operation.cc \
../ns3-mmwave/src/wifi/model/ideal-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/interference-helper.cc \
../ns3-mmwave/src/wifi/model/mac-low.cc \
../ns3-mmwave/src/wifi/model/mac-rx-middle.cc \
../ns3-mmwave/src/wifi/model/mac-tx-middle.cc \
../ns3-mmwave/src/wifi/model/mgt-headers.cc \
../ns3-mmwave/src/wifi/model/minstrel-ht-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/minstrel-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/mpdu-aggregator.cc \
../ns3-mmwave/src/wifi/model/mpdu-standard-aggregator.cc \
../ns3-mmwave/src/wifi/model/msdu-aggregator.cc \
../ns3-mmwave/src/wifi/model/msdu-standard-aggregator.cc \
../ns3-mmwave/src/wifi/model/nist-error-rate-model.cc \
../ns3-mmwave/src/wifi/model/onoe-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/originator-block-ack-agreement.cc \
../ns3-mmwave/src/wifi/model/parf-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/qos-blocked-destinations.cc \
../ns3-mmwave/src/wifi/model/qos-utils.cc \
../ns3-mmwave/src/wifi/model/random-stream.cc \
../ns3-mmwave/src/wifi/model/regular-wifi-mac.cc \
../ns3-mmwave/src/wifi/model/rraa-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/rrpaa-wifi-manager.cc \
../ns3-mmwave/src/wifi/model/snr-tag.cc \
../ns3-mmwave/src/wifi/model/spectrum-wifi-phy.cc \
../ns3-mmwave/src/wifi/model/ssid.cc \
../ns3-mmwave/src/wifi/model/sta-wifi-mac.cc \
../ns3-mmwave/src/wifi/model/status-code.cc \
../ns3-mmwave/src/wifi/model/supported-rates.cc \
../ns3-mmwave/src/wifi/model/vht-capabilities.cc \
../ns3-mmwave/src/wifi/model/vht-operation.cc \
../ns3-mmwave/src/wifi/model/wifi-information-element-vector.cc \
../ns3-mmwave/src/wifi/model/wifi-information-element.cc \
../ns3-mmwave/src/wifi/model/wifi-mac-header.cc \
../ns3-mmwave/src/wifi/model/wifi-mac-queue.cc \
../ns3-mmwave/src/wifi/model/wifi-mac-trailer.cc \
../ns3-mmwave/src/wifi/model/wifi-mac.cc \
../ns3-mmwave/src/wifi/model/wifi-mode.cc \
../ns3-mmwave/src/wifi/model/wifi-net-device.cc \
../ns3-mmwave/src/wifi/model/wifi-phy-state-helper.cc \
../ns3-mmwave/src/wifi/model/wifi-phy-tag.cc \
../ns3-mmwave/src/wifi/model/wifi-phy.cc \
../ns3-mmwave/src/wifi/model/wifi-radio-energy-model.cc \
../ns3-mmwave/src/wifi/model/wifi-remote-station-manager.cc \
../ns3-mmwave/src/wifi/model/wifi-spectrum-phy-interface.cc \
../ns3-mmwave/src/wifi/model/wifi-spectrum-signal-parameters.cc \
../ns3-mmwave/src/wifi/model/wifi-tx-current-model.cc \
../ns3-mmwave/src/wifi/model/wifi-tx-vector.cc \
../ns3-mmwave/src/wifi/model/wifi-utils.cc \
../ns3-mmwave/src/wifi/model/yans-error-rate-model.cc \
../ns3-mmwave/src/wifi/model/yans-wifi-channel.cc \
../ns3-mmwave/src/wifi/model/yans-wifi-phy.cc 

CC_DEPS += \
./ns3-mmwave/src/wifi/model/aarf-wifi-manager.d \
./ns3-mmwave/src/wifi/model/aarfcd-wifi-manager.d \
./ns3-mmwave/src/wifi/model/adhoc-wifi-mac.d \
./ns3-mmwave/src/wifi/model/ampdu-subframe-header.d \
./ns3-mmwave/src/wifi/model/ampdu-tag.d \
./ns3-mmwave/src/wifi/model/amrr-wifi-manager.d \
./ns3-mmwave/src/wifi/model/amsdu-subframe-header.d \
./ns3-mmwave/src/wifi/model/ap-wifi-mac.d \
./ns3-mmwave/src/wifi/model/aparf-wifi-manager.d \
./ns3-mmwave/src/wifi/model/arf-wifi-manager.d \
./ns3-mmwave/src/wifi/model/block-ack-agreement.d \
./ns3-mmwave/src/wifi/model/block-ack-cache.d \
./ns3-mmwave/src/wifi/model/block-ack-manager.d \
./ns3-mmwave/src/wifi/model/capability-information.d \
./ns3-mmwave/src/wifi/model/cara-wifi-manager.d \
./ns3-mmwave/src/wifi/model/constant-rate-wifi-manager.d \
./ns3-mmwave/src/wifi/model/ctrl-headers.d \
./ns3-mmwave/src/wifi/model/dca-txop.d \
./ns3-mmwave/src/wifi/model/dcf-manager.d \
./ns3-mmwave/src/wifi/model/dcf-state.d \
./ns3-mmwave/src/wifi/model/dsss-error-rate-model.d \
./ns3-mmwave/src/wifi/model/dsss-parameter-set.d \
./ns3-mmwave/src/wifi/model/edca-parameter-set.d \
./ns3-mmwave/src/wifi/model/edca-txop-n.d \
./ns3-mmwave/src/wifi/model/erp-information.d \
./ns3-mmwave/src/wifi/model/error-rate-model.d \
./ns3-mmwave/src/wifi/model/he-capabilities.d \
./ns3-mmwave/src/wifi/model/ht-capabilities.d \
./ns3-mmwave/src/wifi/model/ht-operation.d \
./ns3-mmwave/src/wifi/model/ideal-wifi-manager.d \
./ns3-mmwave/src/wifi/model/interference-helper.d \
./ns3-mmwave/src/wifi/model/mac-low.d \
./ns3-mmwave/src/wifi/model/mac-rx-middle.d \
./ns3-mmwave/src/wifi/model/mac-tx-middle.d \
./ns3-mmwave/src/wifi/model/mgt-headers.d \
./ns3-mmwave/src/wifi/model/minstrel-ht-wifi-manager.d \
./ns3-mmwave/src/wifi/model/minstrel-wifi-manager.d \
./ns3-mmwave/src/wifi/model/mpdu-aggregator.d \
./ns3-mmwave/src/wifi/model/mpdu-standard-aggregator.d \
./ns3-mmwave/src/wifi/model/msdu-aggregator.d \
./ns3-mmwave/src/wifi/model/msdu-standard-aggregator.d \
./ns3-mmwave/src/wifi/model/nist-error-rate-model.d \
./ns3-mmwave/src/wifi/model/onoe-wifi-manager.d \
./ns3-mmwave/src/wifi/model/originator-block-ack-agreement.d \
./ns3-mmwave/src/wifi/model/parf-wifi-manager.d \
./ns3-mmwave/src/wifi/model/qos-blocked-destinations.d \
./ns3-mmwave/src/wifi/model/qos-utils.d \
./ns3-mmwave/src/wifi/model/random-stream.d \
./ns3-mmwave/src/wifi/model/regular-wifi-mac.d \
./ns3-mmwave/src/wifi/model/rraa-wifi-manager.d \
./ns3-mmwave/src/wifi/model/rrpaa-wifi-manager.d \
./ns3-mmwave/src/wifi/model/snr-tag.d \
./ns3-mmwave/src/wifi/model/spectrum-wifi-phy.d \
./ns3-mmwave/src/wifi/model/ssid.d \
./ns3-mmwave/src/wifi/model/sta-wifi-mac.d \
./ns3-mmwave/src/wifi/model/status-code.d \
./ns3-mmwave/src/wifi/model/supported-rates.d \
./ns3-mmwave/src/wifi/model/vht-capabilities.d \
./ns3-mmwave/src/wifi/model/vht-operation.d \
./ns3-mmwave/src/wifi/model/wifi-information-element-vector.d \
./ns3-mmwave/src/wifi/model/wifi-information-element.d \
./ns3-mmwave/src/wifi/model/wifi-mac-header.d \
./ns3-mmwave/src/wifi/model/wifi-mac-queue.d \
./ns3-mmwave/src/wifi/model/wifi-mac-trailer.d \
./ns3-mmwave/src/wifi/model/wifi-mac.d \
./ns3-mmwave/src/wifi/model/wifi-mode.d \
./ns3-mmwave/src/wifi/model/wifi-net-device.d \
./ns3-mmwave/src/wifi/model/wifi-phy-state-helper.d \
./ns3-mmwave/src/wifi/model/wifi-phy-tag.d \
./ns3-mmwave/src/wifi/model/wifi-phy.d \
./ns3-mmwave/src/wifi/model/wifi-radio-energy-model.d \
./ns3-mmwave/src/wifi/model/wifi-remote-station-manager.d \
./ns3-mmwave/src/wifi/model/wifi-spectrum-phy-interface.d \
./ns3-mmwave/src/wifi/model/wifi-spectrum-signal-parameters.d \
./ns3-mmwave/src/wifi/model/wifi-tx-current-model.d \
./ns3-mmwave/src/wifi/model/wifi-tx-vector.d \
./ns3-mmwave/src/wifi/model/wifi-utils.d \
./ns3-mmwave/src/wifi/model/yans-error-rate-model.d \
./ns3-mmwave/src/wifi/model/yans-wifi-channel.d \
./ns3-mmwave/src/wifi/model/yans-wifi-phy.d 

OBJS += \
./ns3-mmwave/src/wifi/model/aarf-wifi-manager.o \
./ns3-mmwave/src/wifi/model/aarfcd-wifi-manager.o \
./ns3-mmwave/src/wifi/model/adhoc-wifi-mac.o \
./ns3-mmwave/src/wifi/model/ampdu-subframe-header.o \
./ns3-mmwave/src/wifi/model/ampdu-tag.o \
./ns3-mmwave/src/wifi/model/amrr-wifi-manager.o \
./ns3-mmwave/src/wifi/model/amsdu-subframe-header.o \
./ns3-mmwave/src/wifi/model/ap-wifi-mac.o \
./ns3-mmwave/src/wifi/model/aparf-wifi-manager.o \
./ns3-mmwave/src/wifi/model/arf-wifi-manager.o \
./ns3-mmwave/src/wifi/model/block-ack-agreement.o \
./ns3-mmwave/src/wifi/model/block-ack-cache.o \
./ns3-mmwave/src/wifi/model/block-ack-manager.o \
./ns3-mmwave/src/wifi/model/capability-information.o \
./ns3-mmwave/src/wifi/model/cara-wifi-manager.o \
./ns3-mmwave/src/wifi/model/constant-rate-wifi-manager.o \
./ns3-mmwave/src/wifi/model/ctrl-headers.o \
./ns3-mmwave/src/wifi/model/dca-txop.o \
./ns3-mmwave/src/wifi/model/dcf-manager.o \
./ns3-mmwave/src/wifi/model/dcf-state.o \
./ns3-mmwave/src/wifi/model/dsss-error-rate-model.o \
./ns3-mmwave/src/wifi/model/dsss-parameter-set.o \
./ns3-mmwave/src/wifi/model/edca-parameter-set.o \
./ns3-mmwave/src/wifi/model/edca-txop-n.o \
./ns3-mmwave/src/wifi/model/erp-information.o \
./ns3-mmwave/src/wifi/model/error-rate-model.o \
./ns3-mmwave/src/wifi/model/he-capabilities.o \
./ns3-mmwave/src/wifi/model/ht-capabilities.o \
./ns3-mmwave/src/wifi/model/ht-operation.o \
./ns3-mmwave/src/wifi/model/ideal-wifi-manager.o \
./ns3-mmwave/src/wifi/model/interference-helper.o \
./ns3-mmwave/src/wifi/model/mac-low.o \
./ns3-mmwave/src/wifi/model/mac-rx-middle.o \
./ns3-mmwave/src/wifi/model/mac-tx-middle.o \
./ns3-mmwave/src/wifi/model/mgt-headers.o \
./ns3-mmwave/src/wifi/model/minstrel-ht-wifi-manager.o \
./ns3-mmwave/src/wifi/model/minstrel-wifi-manager.o \
./ns3-mmwave/src/wifi/model/mpdu-aggregator.o \
./ns3-mmwave/src/wifi/model/mpdu-standard-aggregator.o \
./ns3-mmwave/src/wifi/model/msdu-aggregator.o \
./ns3-mmwave/src/wifi/model/msdu-standard-aggregator.o \
./ns3-mmwave/src/wifi/model/nist-error-rate-model.o \
./ns3-mmwave/src/wifi/model/onoe-wifi-manager.o \
./ns3-mmwave/src/wifi/model/originator-block-ack-agreement.o \
./ns3-mmwave/src/wifi/model/parf-wifi-manager.o \
./ns3-mmwave/src/wifi/model/qos-blocked-destinations.o \
./ns3-mmwave/src/wifi/model/qos-utils.o \
./ns3-mmwave/src/wifi/model/random-stream.o \
./ns3-mmwave/src/wifi/model/regular-wifi-mac.o \
./ns3-mmwave/src/wifi/model/rraa-wifi-manager.o \
./ns3-mmwave/src/wifi/model/rrpaa-wifi-manager.o \
./ns3-mmwave/src/wifi/model/snr-tag.o \
./ns3-mmwave/src/wifi/model/spectrum-wifi-phy.o \
./ns3-mmwave/src/wifi/model/ssid.o \
./ns3-mmwave/src/wifi/model/sta-wifi-mac.o \
./ns3-mmwave/src/wifi/model/status-code.o \
./ns3-mmwave/src/wifi/model/supported-rates.o \
./ns3-mmwave/src/wifi/model/vht-capabilities.o \
./ns3-mmwave/src/wifi/model/vht-operation.o \
./ns3-mmwave/src/wifi/model/wifi-information-element-vector.o \
./ns3-mmwave/src/wifi/model/wifi-information-element.o \
./ns3-mmwave/src/wifi/model/wifi-mac-header.o \
./ns3-mmwave/src/wifi/model/wifi-mac-queue.o \
./ns3-mmwave/src/wifi/model/wifi-mac-trailer.o \
./ns3-mmwave/src/wifi/model/wifi-mac.o \
./ns3-mmwave/src/wifi/model/wifi-mode.o \
./ns3-mmwave/src/wifi/model/wifi-net-device.o \
./ns3-mmwave/src/wifi/model/wifi-phy-state-helper.o \
./ns3-mmwave/src/wifi/model/wifi-phy-tag.o \
./ns3-mmwave/src/wifi/model/wifi-phy.o \
./ns3-mmwave/src/wifi/model/wifi-radio-energy-model.o \
./ns3-mmwave/src/wifi/model/wifi-remote-station-manager.o \
./ns3-mmwave/src/wifi/model/wifi-spectrum-phy-interface.o \
./ns3-mmwave/src/wifi/model/wifi-spectrum-signal-parameters.o \
./ns3-mmwave/src/wifi/model/wifi-tx-current-model.o \
./ns3-mmwave/src/wifi/model/wifi-tx-vector.o \
./ns3-mmwave/src/wifi/model/wifi-utils.o \
./ns3-mmwave/src/wifi/model/yans-error-rate-model.o \
./ns3-mmwave/src/wifi/model/yans-wifi-channel.o \
./ns3-mmwave/src/wifi/model/yans-wifi-phy.o 


# Each subdirectory must supply rules for building sources it contributes
ns3-mmwave/src/wifi/model/%.o: ../ns3-mmwave/src/wifi/model/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


